<?php

/**
 * @file
 * Primary module hooks for anytown module.
 */
use Drupal\anytown\Hook\AnytownTheme;

// Delegates theme hook function to the OOP implementation.
// Calls its theme() method and return the results.
// https://www.hashbangcode.com/article/drupal-11-object-oriented-hooks-and-hook-service-classes
#[LegacyHook]
  function anytown_theme($existing, $type, $theme, $path) {
    $handler = \Drupal::classResolver()->getInstanceFromDefinition(AnytownTheme::class);
    return $handler->theme();
  }
